### ISSUE TITLE
Filters don't return string

### ISSUE THREAD

**Issue by ghost** [strawbrary/koa-nunjucks-2#28]
Middleware

````
koa.use( Nunjucks( {
    ext: 'html',
    path: Path.join( __dirname, '/../templates' ),
    nunjucksConfig: {
      trimBlocks: true
    },
    configureEnvironment: ( env ) => {

      env.addFilter( 'testing', ( str, count ) => {
        console.log( str );
        console.log( count );
        return str;
      } );

    }
} ) );
````

Nunjucks html

`{{ hello | testing(23) }}`

Result

````
undefined
23
````

Perhaps something dead obvious that's going right by me?

**Comment by ghost** [comment]
For the string to be included, then it needs to be wrapped in quotes.

`{{ "hello" | testing(23 }}`

As far as I know, then this is not standard Nunjucks behavior, any specific reason the quotes are required in this library?

**Comment by strawbrary** [comment]
When you use the double brackets, Nunjucks evaluates it as a variable, so in your example it's looking for a variable bound to your template context called `hello` which hasn't been defined, hence the reason you're getting `undefined` logged. If you still want it to be a variable, you'll need to pass an object with the `hello` key defined into your `render()` call, otherwise use quotes for a string literal.
